##
## EPITECH PROJECT, 2021
## zappy
## File description:
## Makefile
##

BIN			=	zappy_ai
FILE		=	zappy_ai.py

all:
	make compil

re:
	make fclean
	make compil

compil:
	cp $(FILE) $(BIN)
	chmod 755 $(BIN)

clean:

fclean:
	rm -f $(BIN)
	make clean